---
title: "StreetMap Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
# source(here::here('R/setup.R'))
source(here::here('R/munis_df.R'))
```

## Load data


```{r cars}
validated_sample_df <- 
  read_csv("../../../data/geocode/streetmap_eval/validated_sample_gmaps_bsb.csv") %>%
  mutate(geocode_result = case_when(geocode_distance <= 0 ~ "VALID",
                                  geocode_distance <= 350 ~ "GOOD",
                                  geocode_distance <= 1000 ~ "AVERAGE",
                                  TRUE ~ "BAD")) %>%
  filter(city == "Brasília")

unique(validated_sample_df$geocode_precision)
geocode_type_levels <- unique(validated_sample_df$geocode_precision)
# geocode_type_levels <- c("PointAddress", "StreetAddress", "StreetAddressExt", 
                         # "StreetName", "POI",
                         # "PostalExt", "PostalLoc", "Postal", "Locality", "DistanceMarker")
```

## Data preparation


```{r pressure, echo=FALSE}
validated_count_df <- validated_sample_df %>%
  count(city, geocode_result)


city_order <- validated_count_df %>%
  pivot_wider(names_from = geocode_result, values_from = n) %>%
  ungroup() %>%
  arrange(VALID, GOOD, AVERAGE, BAD)

city_order_p  <- validated_count_df %>%
  group_by(city) %>%
  mutate(n = n / sum(n)) %>%
  pivot_wider(names_from = geocode_result, values_from = n) %>%
  ungroup() %>%
  arrange(VALID, GOOD, AVERAGE, BAD)

validated_count_df <- validated_count_df %>%
  mutate(city = factor(city, levels = city_order$city),
         geocode_result = factor(geocode_result,
                                 levels = c("VALID", "GOOD", "AVERAGE", "BAD"),
                                 labels = c("VALID", "GOOD (< 350m)", "AVERAGE (< 1km)", "BAD"))) %>%
  mutate(geocode_result = fct_rev(geocode_result))

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


## Resultados

### Por Município

#### Absoluto

```{r}
validated_count_df %>%
  ggplot() + geom_col(aes(x = city, y = n, fill = geocode_result)) +
  coord_flip() +
  scale_fill_brewer(palette = "Spectral", direction = 1, guide = guide_legend(reverse = TRUE)) +
  scale_y_continuous(breaks = seq(0, 25000, 2500), minor_breaks = seq(0, 25000, 1250)) +
  labs(title = "Resultado geral do geocoding, por município",
       x = NULL, y = NULL, fill = NULL,
       caption = "VALID: dentro do setor censitário\nGOOD: até 350m do setor censitário\nAVERAGE: até 1km do setor censitário\nBAD: acima de 1km do setor censitário"
  )

```

#### Relativo

```{r}
validated_count_df %>%
  group_by(city) %>%
  mutate(p = n / sum(n)) %>%
  mutate(city = factor(city, levels = city_order_p$city)) %>%
  ggplot() + geom_col(aes(x = city, y = p, fill = geocode_result)) +
  coord_flip() +
  scale_fill_brewer(palette = "Spectral", direction = 1, guide = guide_legend(reverse = TRUE)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Resultado geral do geocoding, por município",
       x = NULL, y = NULL, fill = NULL,
       caption = "VALID: dentro do setor censitário\nGOOD: até 350m do setor censitário\nAVERAGE: até 1km do setor censitário\nBAD: acima de 1km do setor censitário"  )


```


### Por ADDR_TYPE

#### Relativo

```{r}
validated_sample_df %>%
  count(geocode_precision, geocode_result) %>%
  group_by(geocode_precision) %>%
  mutate(p = n / sum(n)) %>%
  mutate(geocode_type = factor(geocode_precision, levels = geocode_type_levels)) %>%
  mutate(geocode_type = fct_rev(geocode_type)) %>%
  mutate(geocode_result = factor(geocode_result,
                                 levels = c("VALID", "GOOD", "AVERAGE", "BAD"),
                                 labels = c("VALID", "GOOD (< 350m)", "AVERAGE (< 1km)", "BAD"))) %>%
  mutate(geocode_result = fct_rev(geocode_result)) %>%
  ggplot() + geom_col(aes(x = geocode_type, y = p, fill = geocode_result)) +
  coord_flip() +
  scale_fill_brewer(palette = "Spectral", direction = 1, guide = guide_legend(reverse = TRUE)) +
  scale_y_continuous(labels = scales::percent) +
  # scale_y_continuous(breaks = seq(0, 1000, 100), minor_breaks = seq(0, 1000, 50)) +
  labs(title = "Resultado geral do geocoding, por ADDR_TYPE",
       x = NULL, y = NULL, fill = NULL#,
       # caption = "VALID: dentro do setor censitário\nGOOD: até 350m do setor censitário\nAVERAGE: até #1km do setor censitário\nBAD: acima de 1km do setor censitário"
  ) +
  theme(legend.position = "right")
```

#### Absoluto

```{r}
validated_sample_df %>%
  count(geocode_precision, geocode_result) %>%
  group_by(geocode_precision) %>%
  mutate(p = n / sum(n)) %>%
  mutate(geocode_type = factor(geocode_precision, levels = geocode_type_levels)) %>%
  mutate(geocode_type = fct_rev(geocode_type)) %>%
  mutate(geocode_result = factor(geocode_result,
                                 levels = c("VALID", "GOOD", "AVERAGE", "BAD"),
                                 labels = c("VALID", "GOOD (< 350m)", "AVERAGE (< 1km)", "BAD"))) %>%
  mutate(geocode_result = fct_rev(geocode_result)) %>%
  ggplot() + geom_col(aes(x = geocode_type, y = n, fill = geocode_result)) +
  coord_flip() +
  scale_fill_brewer(palette = "Spectral", direction = 1, guide = guide_legend(reverse = TRUE)) +
  # scale_y_percent() +
  scale_y_continuous(breaks = seq(0, 25000, 2500), minor_breaks = seq(0, 25000, 1250)) +
  labs(title = "Resultado geral do geocoding, por ADDR_TYPE",
       x = NULL, y = NULL, fill = NULL
  ) +
  theme(legend.position = "bottom")

```





